### ISSUE TITLE
Acceptance tests failing

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-civo#118]
Our acceptance tests (all of them) are failing with the following message:

```
[ERR] failed to get the default network: DatabaseAccountNotFoundError: Failed to find the account within the internal database
```

Consider updating the provider to see if it resolves the issue. These tests have been broken for a while, but we did not detect them because gotestfmt was still returning zero.

**Comment by stack72** [comment]
This now working - we had to recycle the API Key
