### ISSUE TITLE
Issues with pulumi-civo provider

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-civo#135]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

When I create a new Pulumi civo project, i get following error:

```bash
/Users/dirien/Tools/repos/templates-civo/civo-temp/go.mod:6:2: require github.com/pulumi/pulumi-civo/sdk: version "v2.2.0" invalid: should be v0 or v1, not v2
error: `go mod tidy` failed to install dependencies; rerun manually to try again, then run 'pulumi up' to perform an initial deployment: exit status 1
````

When i try to update the go librarary by hand, I get follwing error!
```bash
❯ go get -u github.com/pulumi/pulumi-civo/sdk/v2
go: errors parsing go.mod:
/Users/dirien/Tools/repos/templates-civo/civo-temp/go.mod:6:2: require github.com/pulumi/pulumi-civo/sdk: version "v2.2.0" invalid: should be v0 or v1, not v2
```

Only `github.com/pulumi/pulumi-civo/sdk/v2 v2.1.4` is working but when I try to run `pulumi up` I get :

```bash
Diagnostics:
  pulumi:providers:civo (default):
    error: no resource plugin 'pulumi-resource-civo' found in the workspace at version v2.1.4 or on your $PATH, install the plugin using `pulumi plugin install resource civo v2.1.4`
```

Any hints on what I do wrong?

### Steps to reproduce

1.
2.
3.
4.

Expected: 
Actual:

**Comment by stack72** [comment]
Hey @dirien 

It looks like there was an issue with the Go SDK tag - can you try again? It feels correct for me now based on my local testing

Paul

**Comment by dirien** [comment]
still get 

```
/Users/dirien/Tools/repos/templates-civo/civo-temp/go.mod:6:2: require github.com/pulumi/pulumi-civo/sdk: version "v2.2.0" invalid: should be v0 or v1, not v2
```

with 

```go
module dsd

go 1.18

require (
	github.com/pulumi/pulumi-civo/sdk v2.2.0
	github.com/pulumi/pulumi/sdk/v3 v3.26.1
)
```

**Comment by dirien** [comment]
Ok,

it must be `github.com/pulumi/pulumi-civo/sdk/v2` than it works! 

Thanks Paul!

**Comment by stack72** [comment]
thanks! I will merge your PR for templates now to fix this up!
