### ISSUE TITLE
Unable to Create Civo Kubernetes Cluster

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-civo#141]
### What happened?

Hi,

when i try to create a Civo Cluster (`pulumi up`) i get in the first run following error message: 

```bash
civo:index:KubernetesCluster (civo-k3s-cluster):
    error: 1 error occurred:
        * creating urn:pulumi:dev::00-civo::civo:index/kubernetesCluster:KubernetesCluster::civo-k3s-cluster: 1 error occurred:
        * error waiting for cluster (c203182f-617e-422a-9365-49f05c527fc3) to be created: unexpected state 'AVAILABLE', wanted target 'ACTIVE'. last error: %!s(<nil>)
```

If I run the `pulumi up` again it works fine.

I use version `v2.2.1` of the `pulumi provider`

### Steps to reproduce

Try to create a Civo Cluster (in go)

### Expected Behavior

Cluster gets created succesfully

### Actual Behavior

Error message, cluster gets created in the background

### Versions used

v3.29.1

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
Thank you for reporting this issue - we'll take a look as soon as we can!

**Comment by guineveresaenger** [comment]
Hi @dirien - we just released a [new version of this provider](https://github.com/pulumi/pulumi-civo/releases/tag/v2.2.2) - can you try it and see if the problem persists?

**Comment by dirien** [comment]
Hi @guineveresaenger,

Looks good so far ! It's one of the issues you can't reproduce :( 
Thanks for your help.
