### ISSUE TITLE
Registry docs not being published

### ISSUE THREAD

**Issue by guineveresaenger** [pulumi/pulumi-civo#174]
https://github.com/pulumi/pulumi-civo/pull/171 was merged and v2.3.1 was cut yesterday, but the [registry still shows v2.3.0](https://www.pulumi.com/registry/packages/civo/).

Yet the [docs-build step](https://github.com/pulumi/pulumi-civo/actions/runs/3886014990/jobs/6630923390) succeeded.

**Comment by susanev** [comment]
relevant?
https://github.com/pulumi/registry/actions/runs/3886159464/jobs/6630926866

**Comment by guineveresaenger** [comment]
yes! thank you!

**Comment by susanev** [comment]
fixed as of https://github.com/pulumi/registry/pull/1911f
